language: bash

services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker version
  - docker info
  - IMAGE=$(echo $TRAVIS_REPO_SLUG | sed 's/\/docker-/\//g')

script:
  - travis_retry docker build -t "$IMAGE" .
  - ~/official-images/test/run.sh "$IMAGE"

after_success:
  - set -ex
  - |
    TAGS=""
    if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      read -a v <<< $(echo ${TRAVIS_TAG} | sed 's/[\.\-]/ /g')
      TAGS="$TRAVIS_TAG ${v[0]}.${v[1]}.${v[2]} ${v[0]}.${v[1]} ${v[0]}"
    elif [[ $TRAVIS_BRANCH =~ master ]]; then
      TAGS="latest"
    elif [[ $TRAVIS_BRANCH =~ ^[0-9]+\. ]]; then
      TAGS="$TRAVIS_BRANCH"
    fi
  - |
    for TAG in $TAGS; do
      docker tag "$IMAGE" "$IMAGE":"$TAG"
      docker push "$IMAGE":"$TAG"
    done
